name: Deploy to EC2

on:
  push:
    branches:
      - master  # Jab aap `master` branch par push karenge, action trigger hoga

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Updated to v3

    - name: Set up Node.js
      uses: actions/setup-node@v3  # Updated to v3
      with:
        node-version: '20' 

    - name: Copy files via SSH
      uses: appleboy/scp-action@v0.1.2
      with:
        host: ec2-16-16-246-83.eu-north-1.compute.amazonaws.com
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}  # Aapka EC2 private key secret hoga
        source: "./"  # Jo bhi aap push kar rahe hain, wo copy hoga
        target: "~/Pizeonfly_crm"  # Target location on server

    - name: Execute SSH command to deploy
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ec2-16-16-246-83.eu-north-1.compute.amazonaws.com
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}  # EC2 SSH private key
        script: |
          cd ~/Pizeonfly_crm
          git pull origin master
          npm install
          pm2 restart all
