name: Node.js CI/CD

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # Install dependencies
    - run: npm ci

    # Install pm2 globally
    - run: npm install -g pm2

    # Build the project (if necessary)
    - run: npm run build --if-present

    # SSH into the EC2 instance and deploy
    - name: SSH and deploy
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ec2-16-16-246-83.eu-north-1.compute.amazonaws.com
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}  # Add your SSH private key to GitHub Secrets
        script: |
          cd ~/Pizeonfly_crm
          git pull origin master
          pm2 restart all

    # Set environment variables on the server
    - name: Set environment variables
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ec2-16-16-246-83.eu-north-1.compute.amazonaws.com
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd ~/Pizeonfly_crm
          touch .env
          echo "${{ secrets.CRM_ENV_FILE }}" > .env
