name: Node.js CI/CD

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # Install dependencies
    - run: npm ci

    # Install pm2 globally
    - run: npm install -g pm2

    # Build the project (if necessary)
    - run: npm run build --if-present

    # Restart pm2 processes
    - run: pm2 restart CRM

    # Set environment variables
    - run: |
        touch .env
        echo "${{secrets.CRM_ENV_FILE}}" > .env
